query-timeout: 10
cache-expire-seconds: 3600
ticket-display-name: "&f&lカプセルトイ券"
ticket-lore1: "地下鉄中央駅のカプセルトイで使えます。"
ticket-lore2: "カプセルトイコードは他人にわからないようにしてください。"
sign-line1-prefix: "&6&l"
sign-line2-prefix: ""
sign-line3: "&8手にチケットを"
sign-line4: "&8持って右クリック！"
hold-the-ticket: "チケットを右手に持ってください。"
not-found-ticket-code: "チケットコードは使用済みか未登録です。"
not-found-chest1: "カプセルトイのチェストが見つかりません。"
not-found-chest2: "/capsluetoy modify <capsluetoy_name>でチェストをセットしてください。"
not-found-pick: "ハズレました。"
found-pick: "賞品をインベントリに送りました。"
